---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins2
  template:
    metadata:
      labels:
        app: jenkins2
    spec:
      containers:
      - name: jenkins2
        image:  jenkins/jenkins:2.235.1-lts-alpine
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_vol
          - name: docker-socket
            mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-vol
          emptyDir: {}
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
          #  type: File

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins2
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
  selector:
    app: jenkins2

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp2
spec:
  type: NodePort
  ports:
    - port: 50000
      targetPort: 50000
      nodePort: 30004
  selector:
    app: jenkins2
